apiVersion: v1
kind: Secret
metadata:
  name: databricks-credentials
  namespace: argo  # Must match your workflow's namespace
type: Opaque
stringData:
  # Replace these with your NEW generated token
  host: "https://dbc-df7f3a99-a11b.cloud.databricks.com/"
  #token: "dapiafd260681cbb74511dcb9e6aa85b0bb4"