# Training Hyperparameters
epochs: 5
batch_size: 16
learning_rate: 0.001

# Data Settings
data_dir: "./dataset"
img_height: 224
img_width: 224

# System Settings
device: "cpu"   # Change to "cuda" if you have a GPU later
experiment_name: "Fruit_Freshness_v1"