# Training Hyperparameters
epochs: 5
batch_size: 32
learning_rate: 0.001

# Data Settings
data_dir: "./dataset"
img_height: 224
img_width: 224

# System Settings
device: "cpu"   
experiment_name: "Fruit_Freshness_v1"